In [2]:
import pandas as pd
import numpy as np
import json
from pandas.io.json import json_normalize

In [3]:
agenda = pd.read_json("agenda_cultural.json")
agenda.columns

Index(['ID', 'post_author', 'post_date', 'post_date_gmt', 'post_content',
       'post_title', 'post_excerpt', 'post_status', 'comment_status',
       'ping_status', 'post_password', 'post_name', 'to_ping', 'pinged',
       'post_modified', 'post_modified_gmt', 'post_content_filtered',
       'post_parent', 'guid', 'menu_order', 'post_type', 'post_mime_type',
       'comment_count', 'filter', 'id', 'type', 'title', 'featured_media',
       'featured_media_thumbnail', 'featured_media_medium',
       'featured_media_large', 'subtitle', 'subject', 'string_dates',
       'string_times', 'description', 'venue', 'categories_name_list',
       'tags_name_list', 'link', 'occurences', 'StartDate', 'LastDate',
       'price_cat', 'price_val', 'target_audience', 'accessibility'],
      dtype='object')

In [5]:
agendalx = agenda[["ID", "categories_name_list", "title", "venue", "occurences", "LastDate", "price_cat"]]
agendalx.head(5)

,ID,categories_name_list,title,venue,occurences,LastDate,price_cat
0,24138,"{'cinema': {'id': 38, 'slug': 'cinema', 'name'...","{'rendered': '""O Farol"" de Robert Eggers'}","{'espaco-nimas': {'id': 405, 'slug': 'espaco-n...","[2020-02-14, 2020-02-15, 2020-02-16, 2020-02-18]",2020-02-18,unknown
1,24137,"{'musica': {'id': 42, 'slug': 'musica', 'name'...",{'rendered': 'Resistência'},"{'culturgest': {'id': 303, 'slug': 'culturgest...",[2020-02-15],2020-02-15,value
2,24132,"{'ciencia': {'id': 39, 'slug': 'ciencia', 'nam...",{'rendered': 'Dinossauros Explorer'},[],"[2019-12-21, 2019-12-22, 2019-12-23, 2019-12-2...",2020-03-22,
3,24109,"{'cinema': {'id': 38, 'slug': 'cinema', 'name'...",{'rendered': 'Especial Óscares'},"{'espaco-nimas': {'id': 405, 'slug': 'espaco-n...","[2020-02-02, 2020-02-03, 2020-02-04, 2020-02-0...",2020-02-24,unknown
4,24128,"{'danca': {'id': 26, 'slug': 'danca', 'name': ...",{'rendered': 'The Wake of Sleep'},[],[2020-01-29],2020-01-29,free

### Clean venue  and create column

In [7]:
venue = agenda["venue"]

def get_venue(x):
    if type(x) == dict:
        # Return the first key
        return list(x.keys())[0]
    
    return "---"

            
agendalx["Venue Name"] = agendalx["venue"].apply(get_venue)
agendalx.head()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

,ID,categories_name_list,title,venue,occurences,LastDate,price_cat,Venue Name
0,24138,"{'cinema': {'id': 38, 'slug': 'cinema', 'name'...","{'rendered': '""O Farol"" de Robert Eggers'}","{'espaco-nimas': {'id': 405, 'slug': 'espaco-n...","[2020-02-14, 2020-02-15, 2020-02-16, 2020-02-18]",2020-02-18,unknown,espaco-nimas
1,24137,"{'musica': {'id': 42, 'slug': 'musica', 'name'...",{'rendered': 'Resistência'},"{'culturgest': {'id': 303, 'slug': 'culturgest...",[2020-02-15],2020-02-15,value,culturgest
2,24132,"{'ciencia': {'id': 39, 'slug': 'ciencia', 'nam...",{'rendered': 'Dinossauros Explorer'},[],"[2019-12-21, 2019-12-22, 2019-12-23, 2019-12-2...",2020-03-22,,---
3,24109,"{'cinema': {'id': 38, 'slug': 'cinema', 'name'...",{'rendered': 'Especial Óscares'},"{'espaco-nimas': {'id': 405, 'slug': 'espaco-n...","[2020-02-02, 2020-02-03, 2020-02-04, 2020-02-0...",2020-02-24,unknown,espaco-nimas
4,24128,"{'danca': {'id': 26, 'slug': 'danca', 'name': ...",{'rendered': 'The Wake of Sleep'},[],[2020-01-29],2020-01-29,free,---

### Clean date and create column

In [9]:
# no null values
agendalx["LastDate"].isnull().sum()
# to datetime
agendalx["LastDate"] = pd.to_datetime(agendalx["LastDate"])
#month column
agendalx["Month"] = agendalx["LastDate"].dt.month
#quarter column
agendalx["Quarter"] = agendalx["LastDate"].dt.quarter

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

### Clean type of event and create event

In [10]:
def get_event(x):
    if type(x) == dict:
        # Return the first key
        return list(x.keys())[0]
    return "---"
agendalx["categories_name_list"] = agendalx["categories_name_list"].apply(get_event)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [12]:
agendalx.head()

,ID,categories_name_list,title,venue,occurences,LastDate,price_cat,Venue Name,Month,Quarter
0,24138,cinema,"{'rendered': '""O Farol"" de Robert Eggers'}","{'espaco-nimas': {'id': 405, 'slug': 'espaco-n...","[2020-02-14, 2020-02-15, 2020-02-16, 2020-02-18]",2020-02-18,unknown,espaco-nimas,2,1
1,24137,musica,{'rendered': 'Resistência'},"{'culturgest': {'id': 303, 'slug': 'culturgest...",[2020-02-15],2020-02-15,value,culturgest,2,1
2,24132,ciencia,{'rendered': 'Dinossauros Explorer'},[],"[2019-12-21, 2019-12-22, 2019-12-23, 2019-12-2...",2020-03-22,,---,3,1
3,24109,cinema,{'rendered': 'Especial Óscares'},"{'espaco-nimas': {'id': 405, 'slug': 'espaco-n...","[2020-02-02, 2020-02-03, 2020-02-04, 2020-02-0...",2020-02-24,unknown,espaco-nimas,2,1
4,24128,danca,{'rendered': 'The Wake of Sleep'},[],[2020-01-29],2020-01-29,free,---,1,1